---
    version: "2.1"
    services:
      heimdall:
        image: robertjensen/simple-website
        container_name: ${name}
        networks:
          - web
        ports:
          - 80
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${name}.rule=Host(`${name}.cmplab.dk`)"
            - "traefik.http.routers.${name}.entrypoints=https"
            - "traefik.http.routers.${name}.tls=true"
            - "traefik.http.routers.${name}.tls.certresolver=myresolver"
            - "traefik.http.services.${name}.loadBalancer.server.port=80"
    
    networks:
      web:
        external: true
    