apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: simple-website
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host('simple-website.cmplab.dk')
    kind: Rule
    services:
    - name: simple-website
      port: 80
  tls:
    certResolver: letsencrypt

  
