apiVersion: v1
kind: Service
metadata:
  name: simple-website
  labels:
    app: simple-website
spec:
  ports:
    - port: 80
  selector:
    app: simple-website
    tier: frontend
  type: LoadBalancer
  